# Docs: https://rancher.github.io/elemental-toolkit/docs/customizing/general_configuration/
cosign: false
verify: false
install:
  grub-entry-name: "EdgeNode OS"
  system:
    size: 4000
  recovery-system:
    size: 2000
    uri: channel:recovery/cos
upgrade:
  grub-entry-name: "EdgeNode OS"
  recovery-system:
    size: 2000
  system:
    size: 4000
reset:
  grub-entry-name: "EdgeNode OS"
  system:
    size: 4000