# Default cOS OEM configuration file
#
# This file is part of cOS and will get reset during upgrades.
#
# Before you change this file manually,
# consider copying this file to /usr/local/cloud-config or
# copy the file with a prefix starting by 90, e.g. /oem/91_custom.yaml
name: "Default network configuration"
stages:
  initramfs:
    - &hostpersist
      if: '[ ! -f "/run/cos/recovery_mode" ]'
      name: "Persist /etc/hostname"
      commands:
      - |
        # persist hostname
        if [ -s /usr/local/etc/hostname ]; then
          cat /usr/local/etc/hostname > /etc/hostname
        else
          mkdir -p /usr/local/etc
          cp /etc/hostname /usr/local/etc
        fi
    - &hostsfix
      name: "Ensure /etc/hosts contains localhost and hostname"
      commands:
      - |
        LINE="127.0.0.1 localhost $(cat /etc/hostname)"
        if ! grep -q "$LINE" "/etc/hosts"; then
          if [ -f /etc/hosts ]; then
            echo "${$LINE} >> /etc/hosts
          else
            echo "${LINE}" > /etc/hosts
          fi
        fi
    - name: "Ensure resolv.conf symlink"
      commands:
      - ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
  network.after:
    - <<: *hostpersist
    - <<: *hostsfix
