name: "Ensure microk8s is activated and up-to-date in snapd"
stages:
  fs:
    - name: "If microk8s not installed, run installer"
      if: |
        [ ! -d \"/var/snap/microk8s\" ]
      commands:
      - /opt/microk8s/scripts/00-install-microk8s.sh
    - name: "If microk8s installed, upgrade if necessary"
      if: |
        [ -d \"/var/snap/microk8s\" ]
      commands:
      - /opt/microk8s/scripts/00-upgrade-microk8s.sh